README.md, TRANSLATIONS.md
This PR adds a detailed guide for new and current translation maintainers with everything they have to know. I moved it to its own Markdown file as I felt it was too large for README.md.
=> docs: add description for translators

guide/faq.md, guide/syntax.md
Fixed typos in `<template>` and `<Transform>` tags.
=> docs: fix typo

guide/navigation.md
Hi,
I think the icon is wrong in the description of the slide overview :)
=> chore: incorrect icon for slides overview in docs

custom/fonts.md, guide/faq.md, guide/syntax.md
Fix https://github.com/slidevjs/docs/issues/26 and some other typos:
- "fontmatter" to "frontmatter";
- "columns" to "column"
- "digrams" to "diagrams"
=> docs: Fix typo (#26)

resources/learning.md
When writing "Japanese" in Japanese, it is correct to use "日本語" instead of "日本语".
=> Minor notation change

custom/index.md
slidevjs/slidev#421 added the possibility to configure a favicon. Currently, the [docs](https://sli.dev/custom/#frontmatter-configures) lack documentation about this.
=> docs: add favicon frontmatter configure

guide/install.md
The old docker image cannot be found on docker hub any more. I created a new one and add more instructions about how to use it.
=> feat: update install.md to fix the missed docker part

guide/exporting.md
I wanted to export my slides using the dark version of the theme and it took me a while to find this option, I would really appreciate having it right next to the instructions on how to export, specially given the popularity of dark mode these days 😊 
This commit just adds a mention to using the `--dark` option when exporting the slides.
=> docs: add mention to --dark option when exporting

custom/global-layers.md
A small fix for the documentation from the website.
Also, thank you for building Slidev. It's so much fun to use! 🙌
=> docs: typo with NavControls action description

addons/use.md, addons/write-an-addon.md
This PR fixes some typos in `addons/use.md` & `addons/write-an-addon.md`.
=> docs: fix typos in addons/

guide/syntax.md
This was an easy first guess of just supplying the line number 0 to make it skip highlighting any lines (imagine you want to display several code blocks and don't want that other code blocks draw the audience attention)
=> docs: markdown code highlighting for none of the lines

custom/config-shortcuts.md
The docs were missing how to bind shortcuts to multiple keys together.
=> docs: update custom keybindings

custom/index.md
Adding the `.pdf` extension to the `exportFilename` property in the fontmatter is _incorrect_
The `.pdf` extension is appended to the filename in [this part of the code](https://github.com/slidevjs/slidev/blob/main/packages/client/logic/nav.ts#L172)
Leaving this in the docs will cause confusion
=> docs: fix exportFilename

.vitepress/config.js
Not 100% sure if the index name and filters are right, but it's a v3 config, so requires appId
=> docs(search): correct credentials for docsearch

custom/config-shortcuts.md
This documentation update follows new feature from https://github.com/slidevjs/slidev/pull/631
and specifically addresses:
1. Up-to-date documentation with regards to navigation features exposed to custom shortcut bindings
2. Tidy-up this page with header breaks
Note: don't merge until we have a new version released with passing tests. Seems like 0.33.1 [has a failing Cypress test](https://github.com/slidevjs/slidev/runs/6955808143?check_suite_focus=true).
=> docs: update for advanced navigation features

.vitepress/config.js, custom/config-parser.md
Doc related to PR https://github.com/slidevjs/slidev/pull/703 (preparser extensions)
=> docs: add parser customization (preparser, but also link vite config)

guide/index.md
Closes https://github.com/slidevjs/slidev/issues/778
=> fix: use bold instead of code tag to avoid breaking chars on mobile

guide/syntax.md
maxHeight property has no effect without passing unit like `px`
=> docs: update syntax.md

custom/index.md, guide/presenter-mode.md
Add doc for presenter mode and the newly `presenter` option in the frontmatter  from https://github.com/slidevjs/slidev/pull/819
=> feat: add presenter mode documentation

guide/faq.md
Windi docs for grid now live under /utilities/layout/grid instead of just /utilities/grid
=> docs: fix broken link in faq

guide/exporting.md
This PR:
* adds the documentation for the `range` option under the `export` function
* moves the "SPA export" to it's own heading 2 document section 
It turns out, the `range` functionality was already in the code base, however the documentation was missing. 
I took a crack at writing something that would be helpful, but honestly I'm not an English major so it's possible that this could be written a lot better. 
Happy to change / enhance / and looking forward to feedback on how to improve. 
Thanks.
=> docs: add documentation for export range feature Fix #821

guide/syntax.md
Related to https://github.com/slidevjs/slidev/issues/456.
1. The description on Vue Loader docs is awfully outdated, with examples that are no more working.
2. The text is not very helpful to who lands on there from the error message and not familiar with Vue concepts.
=> Update syntax.md: Embedded Styles

guide/animations.md
```
export type BuiltinSlideTransition = 'slide-up' | 'slide-down' | 'slide-left' | 'slide-right' | 'fade' | 'zoom' | 'none'
```
ref https://github.com/slidevjs/slidev/blob/4ac00702da4c3bec521fe8725f596a8eb42d5b23/packages/types/src/config.ts#L306
=> docs: fix typo in builtin slide transitions

guide/hosting.md
=> docs: fix typo in output directory

custom/config-windicss.md
windicss repo doesn't have `grids-col` but I do find `grid-cols` but please check my sanity as I can't get either to work with the example that uses arbitrary values. Possibly related: https://github.com/slidevjs/slidev/issues/938
=> docs: grids-cols to grid-cols

guide/install.md
Noticed that pnpm is not listed, even though the scaffolding CLI specifically supports it
=> docs: add pnpm to install.md instructions

themes/write-a-theme.md
Align examples in `write-a-theme.md` with the following typedefs:
```ts
/**
* Metadata for "slidev" field in themes' package.json
*/
export interface SlidevThemeMeta {
defaults?: Partial<SlidevConfig>
colorSchema?: 'dark' | 'light' | 'both'
highlighter?: 'prism' | 'shiki' | 'both'
}
```
[(source)](https://github.com/slidevjs/slidev/blob/d34da0c84ec48d510902aa913258b06018ca7697/packages/types/src/types.ts#L31C1-L35)
Although 'all' works too as a value for `highlighter`, it makes sense to change it for continuity's sake.
=> docs: align theme docs with types

guide/install.md
To specify output format, use `--format`, not `--base`.
=> docs: fix incorrect option name

themes/use.md
It could be handy to mention [support for themes from scoped packages](https://github.com/slidevjs/slidev/pull/604)  in the docs
=> docs: mention support for scoped packages

builtin/layouts.md
Unnecessary colons were added, so the display was not as intended.
|Before|After|
|---|---|
|![CleanShot 2023-09-01 at 05 03 05](https://github.com/slidevjs/docs/assets/11070996/2aee9b00-c9fa-4337-af94-594a7c751493)|![CleanShot 2023-09-01 at 05 03 21](https://github.com/slidevjs/docs/assets/11070996/6fea3cc8-fac2-4cc4-9595-ab306693e9b2)|
=> docs: remove unnecessary colons

custom/config-monaco.md
Adds documentation for the Monaco EditorOptions implemented in this PR: https://github.com/slidevjs/slidev/pull/1058
=> docs: add monaco editorOptions

guide/hosting.md
Update setup of deployment to GitHub pages. This was commented to work (and the action actually asked for it in my case) [here](https://github.com/actions/configure-pages/issues/40#issuecomment-1407442477).
=> docs: update hosting guide for GitHub Pages

guide/hosting.md
When deploying to GitHub Pages, you must provide the `--base` path to the build in order to properly transform the asset paths.
The docs fail to mention that the `--base` path **must begin and end** with a slash `/{base path}/`. This information _is_ surfaced as a warning in the CLI.
```shell
$ slidev build --base my-repo
(!) "base" option should start with a slash.
```
I would imagine this requirement should be added to the other static hosting options; however, I've only tested with GitHub pages.
=> docs: call out required leading slash in base path

guide/syntax.md
Related to issue https://github.com/slidevjs/slidev/issues/267 that was never documented
=> docs: `at` option in line highlightning

guide/syntax.md
Remove extra space after the regex syntax change
https://github.com/slidevjs/slidev/commit/80be226b201f68f67af8e82d3594558a50c29251#diff-345d7ee55c0f3c8202375b28cf816e5fdf5f246d760624b86ed2e6f22c1510f1R192
Related: https://github.com/slidevjs/slidev/issues/1246#issuecomment-1902759691
=> fix: Remove extra space for props to be parsed correctly

custom/highlighters.md
Fix a few minor typos in https://sli.dev/custom/highlighters.html.
=> Fix typos in Highlighters documentation

builtin/layouts.md
Since https://github.com/slidevjs/slidev/pull/1060 we can change the background size of an image layout, but this is undocumented.
=> docs: layout image: add backgroundSize doc

builtin/components.md
This pr:
- adds documentation for the `cards` prop of the `<Tweet />` component added in slidevjs/slidev#1269
=> docs: add 'cards' prop in Tweet component

vite.config.ts
fix #165
fix https://github.com/slidevjs/slidev/issues/1284
Previously, some components are not automatically imported by `unplugin-vue-components`, which caused the above issue.
=> fix: components not found (#165)

builtin/components.md
ID can be extended with ?time=1234 and then the video starts at 1234 seconds.
Could also be a new prop in the future, but as id prop is already string we can perhaps just use it like suggested and don't introduce breaking changes if somebody already figured this out(?).
=> docs: added info about the possibility to start YouTube video at specific time

guide/syntax.md
Fixed a typo by replacing "and" by "an"
=> docs: fix typo in syntax.md

guide/editors.md
This PR adds docs about `prettier-plugin-slidev`.
=> docs: add docs about the Prettier plugin

custom/highlighters.md
There was a dead link referring to TwoSlash support. The link now refers to an appropriate part of the docs:
[https://sli.dev/guide/syntax#twoslash-integration](https://sli.dev/guide/syntax#twoslash-integration)
I also fixed a minor issue with confusing wording on the same line.
=> chore: typo
