slidevjs/docs

.vitepress/theme/components/Environment.vue
custom/config-vite.md

There was a small spelling mistake with the word `compacitblity` and `learn mode`.

chore: typo

---

.vitepress/showcases.ts
.vitepress/themes.ts

- Add unicorn theme based on [dawntraoz.com](https://dawntraoz.com), made with love.
- Fix edit URLs to add themes and showcases on the docs.

docs: add unicorn theme and fix edit urls

---

.vitepress/themes.ts

Added Penguin theme correctly 🐧

Update themes.ts with Penguin Theme

---

custom/global-layers.md

Add an example footer for pages that can be used quickly.

docs: add example footer for pages

---

.vitepress/showcases.ts

Hi! I added my presentations here

add showcase

---

guide/syntax.md

Signed-off-by: why-not-try-calmer <mrnycticorax@gmail.com>

Added short section on referencing static assets

---

.vitepress/showcases.ts

Add slides about how to Create Icon Package With Vue and Rollup.

Add Showcases

---

builtin/layouts.md

Fix #35
This is a first look of the built-in layouts sections.
Since I've written down intuitively the proposal and usage based on the layout source, I'm pretty sure that @antfu should correct the descriptions :)
**Preview:** [Layouts | Slidev](https://deploy-preview-36--slidev.netlify.app/builtin/layouts.html#built-in-layouts)

docs(builtin): Fill built-in layouts

---

.vitepress/showcases.ts

I recently had to give a talk and thought it would be a perfect opportunity to try slidev!

Add to showcases.ts

---

builtin/layouts.md

Docs for https://github.com/slidevjs/slidev/pull/361

docs: include iframe layouts

---

.vitepress/config.js

docs: typo in sidebar

---

builtin/components.md

feat: add TOC documentation

---

guide/install.md

And make 2 different host types more clear

Update install.md to fix typos about docker section 

---

custom/global-layers.md

add documents for custom-nav-controls

docs: add custom-nav-controls documents

---

custom/index.md

doc related to https://github.com/slidevjs/slidev/pull/550

feat: update config doc

---

guide/syntax.md

Feature added in https://github.com/slidevjs/slidev/pull/650

docs: added description and example usage for auto scroll feature

---

.vitepress/themes.ts

Theme: [slidev-theme-eloc](https://github.com/zthxxx/slides/tree/master/packages/slidev-theme-eloc)
Preview: https://eloc-slidev.vercel.app
Slides used the theme: https://slides.zthxxx.me

docs: add previews of slidev-theme-eloc

---

custom/global-layers.md

footer 组件 对应的应该是全局底层组件  global-bottom

docs: update global-layers.md

---

guide/hosting.md

Thanks so much for creating Sli.dev ❤️

docs: fix typos and tweak grammar

---

guide/exporting.md

As requested in: https://github.com/slidevjs/slidev/pull/739#issuecomment-1288640347

doc: add presenter notes export guide

---

.vitepress/showcases.ts

Add 2022 JSConf Korea presentation link

docs: Update showcase list

---

.vitepress/showcases.ts

link: https://ppt.godkun.top
post: https://mp.weixin.qq.com/s/sZTQJLG8gsOxBVesZ8oOJg

docs:  add slidev ppt template with naive-ui

---

custom/config-parser.md

For incoming https://github.com/slidevjs/slidev/pull/787

docs: update parameters in definePreparserSetup

---

builtin/components.md

Add doc for the newly `LightOrDark` component

feat: add LightOrDark component doc

---

custom/config-mermaid.md

This is an update to show how you can create your own Mermaid theme/styles.

docs: added an example of creating custom Mermaid styles

---

.vitepress/themes.ts

Added the unnamed theme to the theme gallery.

docs: Added the unnamed theme

---

.vitepress/themes.ts

Slidev **Dracula** - One of the best dark theme meets slidev
NPM: [npmjs.com/package/slidev-theme-dracula](https://www.npmjs.com/package/slidev-theme-dracula)
GitHub: [jd-solanki/slidev-theme-dracula](https://github.com/jd-solanki/slidev-theme-dracula)
Regards.

docs(themes): added dracula

---

guide/index.md

As Slidev supports `pnpm`, I've added the creation command for it like npm and yarn.

docs: Added pnpm script

---

custom/index.md
guide/animations.md
guide/exporting.md
guide/hosting.md
guide/syntax.md

Update the doc accordingly to last 0.40.5 release.

docs: updates for 0.40.5

---

guide/faq.md

The windicss test/processor/interpret.test.ts appears to check for both underscores or commas but I could only get underscores to work.

fix: replace commas with underscores in atomic-css

---

guide/syntax.md

Reference: https://github.com/slidevjs/slidev/pull/1012

docs: support setting startLines for codeblocks slidev

---

custom/index.md

For https://github.com/slidevjs/slidev/issues/1015

docs: Document PDF author and keywords

---

guide/animations.md

Added documentation for the view transitions animation.
Relate to: https://github.com/slidevjs/slidev/pull/1101#issuecomment-1703933097

feat: view transitions

---

guide/syntax.md

Releated to https://github.com/slidevjs/slidev/pull/1105

docs: add LaTex line highlighting

---

.vitepress/showcases.ts

Add a simple showcase about Social Engineering with theme [slidev-theme-academic](https://github.com/alexanderdavide/slidev-theme-academic).

docs: update showcase

---

.vitepress/themes.ts

Submitting my theme [slidev-theme-frankfurt](https://github.com/MuTsunTsai/slidev-theme-frankfurt) to the gallery.

feat: add slidev-theme-frankfurt to themes.ts

---

custom/config-unocss.md

This should make it less confusing when trying to understand how the template works

docs: explain that Slidev adds custom UnoCSS shortcuts

---

guide/syntax.md

Related to the confusion in https://github.com/slidevjs/slidev/issues/1246

feat: Add notice to the custom clicks count when using the at directive

---

custom/highlighters.md

docs: fix Shikiji link

---

guide/animations.md
guide/syntax.md

This PR mainly updates changes introduced by https://github.com/slidevjs/slidev/pull/1279.

docs: update docs about click animations

---

custom/index.md
guide/install.md

This PR update docs for changes until [v0.48.0-beta.4](https://github.com/slidevjs/slidev/releases/tag/v0.48.0-beta.4)

docs: update latest features

---

guide/syntax.md

This PR fixes that icon sets should be installed before being used.

docs: fix icons installation guide

---

guide/syntax.md

This PR adds a more detailed explanation about code snippets.

docs: more detailed explain about code snippets

---

custom/config-parser.md

doc update for https://github.com/slidevjs/slidev/pull/1337
NB: needs update if the above PR is not merged in 0.48.0

docs: explain mode parameter for preparser extensions
